name: CI Build Training Image

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci-build-training-image.yaml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/ci-build-training-image.yaml'

jobs:
  docker-build:
    uses: opencloudhuborg/.github/.github/workflows/shared-docker-build.yaml@main
    with:
      repo-name: "wine-classifier-training"
      context: "."
      dockerfile: "Dockerfile"
      push-on-pr: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
